### ISSUE TITLE
Factor out common practices to Gradle documentation

### ISSUE THREAD

**Issue by vlsi** [liutikas/gradle-best-practices#3]
It is great you put the items together, however, it would be great to add them to Gradle documentation.

See https://github.com/gradle/gradle/issues/19057

**Comment by liutikas** [comment]
A bunch of these suggestions are something that Gradle would not take as guidance because they are extremely cautious about legacy support, for example I tried deprecating tasks.create and that patch just stalled as they asked me to fix all of their docs and references to the methods, which is not really realistic. Given that experience, I am unlikely to contribute non bug fixes to Gradle, sorry. Feel free to take this guidance and try upstream it back.
